# Backstage override configuration for your local development environment
organization:
  name: Red Hat demo

catalog:
  locations:
    - type: file
      target: ../../software-templates/scaffolder-templates/nodejs-helloworld-template/template.yaml
      rules:
        - allow: [Template]

scaffolder:
  defaultAuthor:
    name: Janus Scaffolder
    email: janus@redhat.com