# Backstage override configuration for your local development environment
organization:
  name: Red Hat demo

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

catalog:
  locations:
    - type: file
      target: ../../software-templates/scaffolder-templates/nodejs-helloworld-template/template.yaml
      rules:
        - allow: [Template]

integrations:
  github:
    - host: github.com
      apps:
        - $include: github-app-redhat-backstage-demo-credentials.yaml

proxy:
  '/argocd/api':
    target: ${ARGOCD_URL}/api/v1/
    changeOrigin: true
    # only if your argocd api has self-signed cert
    secure: false
    headers:
      Cookie: 'argocd.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE2NzA0MjY4NTEsImlhdCI6MTY3MDQyNjg1MSwianRpIjoiZDFiNGQ4NzgtZTVkYS00MTJkLWJkNzYtMTU5ODQ4NGY5NzYzIn0.1af_1u9ZDyobMrg2S5kJFwOsP47qCYdWyuLUT-bI5To'

scaffolder:
  defaultAuthor:
    name: Janus Scaffolder
    email: janus@redhat.com

kubernetes:
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: ${K8S_URL}
          name: Backstage Demo
          authProvider: 'serviceAccount'
          skipTLSVerify: true
          skipMetricsLookup: true
          serviceAccountToken: ${K8S_TOKEN}
          dashboardUrl: ${K8S_DASHBOARD_URL}
          dashboardApp: standard
#          caData: ${K8S_CONFIG_CA_DATA}
          customResources:
            - group: 'argoproj.io'
              apiVersion: 'v1alpha1'
              plural: 'rollouts'