name: ArgoCD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  login:
    name: OpenShift Login and apply ArgoCD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in and set context
        # In a real workflow, point the 'uses' to a tag.
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          # openshift_username: ${{ env.TEST_USER }}
          # openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
#          certificate_authority_data: ${{ secrets.CA_DATA }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
          insecure_skip_tls_verify: true

      - name: Create/Update ArgoCD app
        run: |
          oc apply -n user1-argocd -f manifests/app.yml