apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${{ values.component_id }}
    backstage.io/kubernetes-id: ${{ values.component_id }}
  name: ${{ values.component_id }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: ${{ values.component_id }}